#pragma once
#include "pch.h"
namespace OBJ_Viewer {

	enum MouseKey {
		MOUSE_KEY_1 = GLFW_MOUSE_BUTTON_1,
		MOUSE_KEY_2 = GLFW_MOUSE_BUTTON_2,
		MOUSE_KEY_3 = GLFW_MOUSE_BUTTON_3,
		MOUSE_KEY_4 = GLFW_MOUSE_BUTTON_4,
		MOUSE_KEY_5 = GLFW_MOUSE_BUTTON_5,
		MOUSE_KEY_6 = GLFW_MOUSE_BUTTON_6,
		MOUSE_KEY_7 = GLFW_MOUSE_BUTTON_7,
		MOUSE_KEY_8 = GLFW_MOUSE_BUTTON_8
	};

}