#pragma once
#include<unordered_map>
#include<GLFW/glfw3.h>
#include"IObserver.h"
namespace OBJ_Viewer
{
	enum KeyState {
		KEY_STATE_UKNOWN = -1,
		KEY_PRESSED = GLFW_PRESS,
		KEY_HELD = GLFW_REPEAT,
		KEY_RELEASED = GLFW_RELEASE,
	};
	class MouseInputStateManager:public IObserver<int, int, int> {
	public:
		KeyState GetButtonState(int button);
	private:
		void Update(MessageType type, int button, int action, int mods) override;
	private:
		std::unordered_map<int, KeyState> m_mouseKeyHashes = {
					{GLFW_MOUSE_BUTTON_1, KEY_RELEASED },
					{GLFW_MOUSE_BUTTON_2, KEY_RELEASED },
					{GLFW_MOUSE_BUTTON_3, KEY_RELEASED },
					{GLFW_MOUSE_BUTTON_4, KEY_RELEASED },
					{GLFW_MOUSE_BUTTON_5, KEY_RELEASED },
					{GLFW_MOUSE_BUTTON_6, KEY_RELEASED },
					{GLFW_MOUSE_BUTTON_7, KEY_RELEASED },
					{GLFW_MOUSE_BUTTON_8, KEY_RELEASED }
		};
	};

	class KeyboardInputStateManager:public IObserver<int, int, int,int> {
	public:
		KeyState GetKeyState(int key);
	private:
		void Update(MessageType type, int key, int scancode, int action, int mods) override;
	private:
	std::unordered_map<int, KeyState> m_keyHashes = {
	{GLFW_KEY_END, KEY_RELEASED },
	{GLFW_KEY_SPACE, KEY_RELEASED},
	{GLFW_KEY_APOSTROPHE, KEY_RELEASED},
	{GLFW_KEY_COMMA, KEY_RELEASED},
	{GLFW_KEY_MINUS, KEY_RELEASED},
	{GLFW_KEY_PERIOD, KEY_RELEASED},
	{GLFW_KEY_SLASH, KEY_RELEASED},
	{GLFW_KEY_0, KEY_RELEASED},
	{GLFW_KEY_1, KEY_RELEASED},
	{GLFW_KEY_2, KEY_RELEASED},
	{GLFW_KEY_3, KEY_RELEASED},
	{GLFW_KEY_4, KEY_RELEASED},
	{GLFW_KEY_5, KEY_RELEASED},
	{GLFW_KEY_6, KEY_RELEASED},
	{GLFW_KEY_7, KEY_RELEASED},
	{GLFW_KEY_8, KEY_RELEASED},
	{GLFW_KEY_9, KEY_RELEASED},
	{GLFW_KEY_SEMICOLON, KEY_RELEASED},
	{GLFW_KEY_EQUAL, KEY_RELEASED},
	{GLFW_KEY_A, KEY_RELEASED},
	{GLFW_KEY_B, KEY_RELEASED},
	{GLFW_KEY_C, KEY_RELEASED},
	{GLFW_KEY_D, KEY_RELEASED},
	{GLFW_KEY_E, KEY_RELEASED},
	{GLFW_KEY_F, KEY_RELEASED},
	{GLFW_KEY_G, KEY_RELEASED},
	{GLFW_KEY_H, KEY_RELEASED},
	{GLFW_KEY_I, KEY_RELEASED},
	{GLFW_KEY_J, KEY_RELEASED},
	{GLFW_KEY_K, KEY_RELEASED},
	{GLFW_KEY_L, KEY_RELEASED},
	{GLFW_KEY_M, KEY_RELEASED},
	{GLFW_KEY_N, KEY_RELEASED},
	{GLFW_KEY_O, KEY_RELEASED},
	{GLFW_KEY_P, KEY_RELEASED},
	{GLFW_KEY_Q, KEY_RELEASED},
	{GLFW_KEY_R, KEY_RELEASED},
	{GLFW_KEY_S, KEY_RELEASED},
	{GLFW_KEY_T, KEY_RELEASED},
	{GLFW_KEY_U, KEY_RELEASED},
	{GLFW_KEY_V, KEY_RELEASED},
	{GLFW_KEY_W, KEY_RELEASED},
	{GLFW_KEY_X, KEY_RELEASED},
	{GLFW_KEY_Y, KEY_RELEASED},
	{GLFW_KEY_Z, KEY_RELEASED},
	{GLFW_KEY_LEFT_BRACKET, KEY_RELEASED},
	{GLFW_KEY_BACKSLASH, KEY_RELEASED},
	{GLFW_KEY_RIGHT_BRACKET, KEY_RELEASED},
	{GLFW_KEY_GRAVE_ACCENT, KEY_RELEASED},
	{GLFW_KEY_WORLD_1, KEY_RELEASED},
	{GLFW_KEY_WORLD_2, KEY_RELEASED},
	{GLFW_KEY_ESCAPE, KEY_RELEASED},
	{GLFW_KEY_ENTER, KEY_RELEASED},
	{GLFW_KEY_TAB, KEY_RELEASED},
	{GLFW_KEY_BACKSPACE, KEY_RELEASED},
	{GLFW_KEY_INSERT, KEY_RELEASED},
	{GLFW_KEY_DELETE, KEY_RELEASED},
	{GLFW_KEY_RIGHT, KEY_RELEASED},
	{GLFW_KEY_LEFT, KEY_RELEASED},
	{GLFW_KEY_DOWN, KEY_RELEASED},
	{GLFW_KEY_UP, KEY_RELEASED},
	{GLFW_KEY_PAGE_UP, KEY_RELEASED},
	{GLFW_KEY_PAGE_DOWN, KEY_RELEASED},
	{GLFW_KEY_HOME, KEY_RELEASED},
	{GLFW_KEY_END, KEY_RELEASED},
	{GLFW_KEY_CAPS_LOCK, KEY_RELEASED},
	{GLFW_KEY_SCROLL_LOCK, KEY_RELEASED},
	{GLFW_KEY_NUM_LOCK, KEY_RELEASED},
	{GLFW_KEY_PRINT_SCREEN, KEY_RELEASED},
	{GLFW_KEY_PAUSE, KEY_RELEASED},
	{GLFW_KEY_F1, KEY_RELEASED},
	{GLFW_KEY_F2, KEY_RELEASED},
	{GLFW_KEY_F3, KEY_RELEASED},
	{GLFW_KEY_F4, KEY_RELEASED},
	{GLFW_KEY_F5, KEY_RELEASED},
	{GLFW_KEY_F6, KEY_RELEASED},
	{GLFW_KEY_F7, KEY_RELEASED},
	{GLFW_KEY_F8, KEY_RELEASED},
	{GLFW_KEY_F9, KEY_RELEASED},
	{GLFW_KEY_F10, KEY_RELEASED},
	{GLFW_KEY_F11, KEY_RELEASED},
	{GLFW_KEY_F12, KEY_RELEASED},
	{GLFW_KEY_F13, KEY_RELEASED},
	{GLFW_KEY_F14, KEY_RELEASED},
	{GLFW_KEY_F15, KEY_RELEASED},
	{GLFW_KEY_F16, KEY_RELEASED},
	{GLFW_KEY_F17, KEY_RELEASED},
	{GLFW_KEY_F18, KEY_RELEASED},
	{GLFW_KEY_F19, KEY_RELEASED},
	{GLFW_KEY_F20, KEY_RELEASED},
	{GLFW_KEY_F21, KEY_RELEASED},
	{GLFW_KEY_F22, KEY_RELEASED},
	{GLFW_KEY_F23, KEY_RELEASED},
	{GLFW_KEY_F24, KEY_RELEASED},
	{GLFW_KEY_F25, KEY_RELEASED},
	{GLFW_KEY_KP_0, KEY_RELEASED},
	{GLFW_KEY_KP_1, KEY_RELEASED},
	{GLFW_KEY_KP_2, KEY_RELEASED},
	{GLFW_KEY_KP_3, KEY_RELEASED},
	{GLFW_KEY_KP_4, KEY_RELEASED},
	{GLFW_KEY_KP_5, KEY_RELEASED},
	{GLFW_KEY_KP_6, KEY_RELEASED},
	{GLFW_KEY_KP_7, KEY_RELEASED},
	{GLFW_KEY_KP_8, KEY_RELEASED},
	{GLFW_KEY_KP_9, KEY_RELEASED},
	{GLFW_KEY_KP_DECIMAL, KEY_RELEASED},
	{GLFW_KEY_KP_DIVIDE, KEY_RELEASED},
	{GLFW_KEY_KP_MULTIPLY, KEY_RELEASED},
	{GLFW_KEY_KP_SUBTRACT, KEY_RELEASED},
	{GLFW_KEY_KP_ADD, KEY_RELEASED},
	{GLFW_KEY_KP_ENTER, KEY_RELEASED},
	{GLFW_KEY_KP_EQUAL, KEY_RELEASED},
	{GLFW_KEY_LEFT_SHIFT, KEY_RELEASED},
	{GLFW_KEY_LEFT_CONTROL, KEY_RELEASED},
	{GLFW_KEY_LEFT_ALT, KEY_RELEASED},
	{GLFW_KEY_LEFT_SUPER, KEY_RELEASED},
	{GLFW_KEY_RIGHT_SHIFT, KEY_RELEASED},
	{GLFW_KEY_RIGHT_CONTROL, KEY_RELEASED},
	{GLFW_KEY_RIGHT_ALT, KEY_RELEASED},
	{GLFW_KEY_RIGHT_SUPER, KEY_RELEASED},
	{GLFW_KEY_MENU, KEY_RELEASED}};
	};

	class InputHandler
	{
	public:
		InputHandler(Notifier<int, int, int>* mouseButtonNotifier, Notifier<int, int, int, int>* keyboardKeyNotifier);
		bool isKeyboardPressed(int keycode) { return m_keyboardInputManager.GetKeyState(keycode) == KEY_PRESSED; }
		bool isKeyboardKeyHeld(int keycode) { return m_keyboardInputManager.GetKeyState(keycode) == KEY_HELD; }
		bool isMouseButtonPressed(int mouseButton) { return m_mouseInputManager.GetButtonState(mouseButton) == KEY_PRESSED; }
		bool isMouseButtonHeld(int mouseButton) { return m_mouseInputManager.GetButtonState(mouseButton) == KEY_HELD; }
		const char* GetCurrentlyFocusedWindow()const { return m_crrentlyFocusedWindowName; }
		void SetCurrentlyFocusedWindow(const char* windowName){ m_crrentlyFocusedWindowName = windowName; }

		KeyState GetKeyState(int keycode);
	private:
		MouseInputStateManager m_mouseInputManager;
		KeyboardInputStateManager m_keyboardInputManager;
		const char* m_crrentlyFocusedWindowName = "SceneWindow";
};
}

