#pragma once
#include "pch.h"
namespace OBJ_Viewer {
	enum TextureFormat
	{
		TEXTURE_FORMAT_UKNOWN = -1,
		TEXTURE_FORMAT_R = GL_RED,
		TEXTURE_FORMAT_RG = GL_RG,
		TEXTURE_FORMAT_RGB = GL_RGB,
		TEXTURE_FORMAT_RGBA = GL_RGBA
	};
	enum TextureInternalFormat {
		TEXTURE_INTERNAL_FORMAT_DEPTH = GL_DEPTH_COMPONENT,
		TEXTURE_INTERNAL_FORMAT_DEPTH_STENCIL = GL_DEPTH_STENCIL,
		TEXTURE_INTERNAL_FORMAT_R = GL_RED,
		TEXTURE_INTERNAL_FORMAT_RG = GL_RG,
		TEXTURE_INTERNAL_FORMAT_RGB = GL_RGB,
		TEXTURE_INTERNAL_FORMAT_RGBA = GL_RGBA,
	};
	enum TextureFilter
	{
		TEXTURE_FILTER_LINEAR = GL_LINEAR,
		TEXTURE_FILTER_NEAREST = GL_NEAREST
	};
	enum TextureWrap
	{
		TEXTURE_WRAP_REPEAT = GL_REPEAT,
		TEXTURE_WRAP_MIRRORED_REPEAT = GL_MIRRORED_REPEAT,
		TEXTURE_WRAP_CLAMP_TO_EDGE = GL_CLAMP_TO_EDGE,

		//TODO:Add more option
	};
	enum TexturePixelDataType
	{
		TEXTURE_PIXEL_DATA_UNSIGNED_BYTE = GL_UNSIGNED_BYTE,
		TEXTURE_PIXEL_DATA_BYTE = GL_BYTE,
		TEXTURE_PIXEL_DATA_UNSIGNED_SHORT = GL_UNSIGNED_SHORT,
		TEXTURE_PIXEL_DATA_SHORT = GL_SHORT,
		TEXTURE_PIXEL_DATA_UNSIGNED_INT = GL_UNSIGNED_INT,
		TEXTURE_PIXEL_DATA_INT = GL_INT,
		TEXTURE_PIXEL_DATA_HALF_FLOAT = GL_HALF_FLOAT,
		TEXTURE_PIXEL_DATA_FLOAT = GL_FLOAT
	};

}